CXX = g++
CXXFLAGS = -g -Wall -Wextra

TARGET = program
SRC = longest_substring_without_repeating.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)