# Makefile for Best Time to Buy and Sell Stock

CXX = g++
CXXFLAGS = -g -Wall -Wextra

TARGET = program
SRC = Reverse_Integer.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
